spring.application.name=llm-support-lab

spring.datasource.url=jdbc:postgresql://localhost:5432/supportlab
spring.datasource.username=supportlab
spring.datasource.password=supportlab

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=supportlab
spring.rabbitmq.password=supportlab